/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

import static java.lang.Math.sqrt;
import static java.lang.StrictMath.pow;

/**
 *
 * @author reinaldo
 */
public class CalcScreen extends javax.swing.JFrame {

    /**
     * Creates new form CalcScreen
     */
    public CalcScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonOpPorcentagem = new javax.swing.JButton();
        jButtonOpRaiz = new javax.swing.JButton();
        jButtonOpPotencia = new javax.swing.JButton();
        jButtonOpLimpar = new javax.swing.JButton();
        jButtonOpClear = new javax.swing.JButton();
        jButtonOpDeletar = new javax.swing.JButton();
        jButtonNum7 = new javax.swing.JButton();
        jButtonNum8 = new javax.swing.JButton();
        jButtonNum9 = new javax.swing.JButton();
        jButtonOpSinal = new javax.swing.JButton();
        jButtonNum0 = new javax.swing.JButton();
        jButtonOpPonto = new javax.swing.JButton();
        jButtonNum4 = new javax.swing.JButton();
        jButtonNum5 = new javax.swing.JButton();
        jButtonNum6 = new javax.swing.JButton();
        jButtonNum1 = new javax.swing.JButton();
        jButtonNum2 = new javax.swing.JButton();
        jButtonNum3 = new javax.swing.JButton();
        jButtonOpMultiplicacao = new javax.swing.JButton();
        jButtonOpSubtracao = new javax.swing.JButton();
        jButtonOpDivUm = new javax.swing.JButton();
        jButtonOpDivisao = new javax.swing.JButton();
        jButtonOpAdicao = new javax.swing.JButton();
        jButtonOpResultado = new javax.swing.JButton();
        Painel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jButtonOpPorcentagem.setBackground(new java.awt.Color(230, 230, 230));
        jButtonOpPorcentagem.setText("%");
        jButtonOpPorcentagem.setBorder(null);
        jButtonOpPorcentagem.setContentAreaFilled(false);
        jButtonOpPorcentagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpPorcentagemActionPerformed(evt);
            }
        });

        jButtonOpRaiz.setBackground(new java.awt.Color(230, 230, 230));
        jButtonOpRaiz.setText("√");
        jButtonOpRaiz.setBorder(null);
        jButtonOpRaiz.setContentAreaFilled(false);
        jButtonOpRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpRaizActionPerformed(evt);
            }
        });

        jButtonOpPotencia.setBackground(new java.awt.Color(230, 230, 230));
        jButtonOpPotencia.setText("x^2");
        jButtonOpPotencia.setBorder(null);
        jButtonOpPotencia.setContentAreaFilled(false);
        jButtonOpPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpPotenciaActionPerformed(evt);
            }
        });

        jButtonOpLimpar.setBackground(new java.awt.Color(230, 230, 230));
        jButtonOpLimpar.setText("CE");
        jButtonOpLimpar.setBorder(null);
        jButtonOpLimpar.setContentAreaFilled(false);
        jButtonOpLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpLimparActionPerformed(evt);
            }
        });

        jButtonOpClear.setBackground(new java.awt.Color(230, 230, 230));
        jButtonOpClear.setText("C");
        jButtonOpClear.setBorder(null);
        jButtonOpClear.setContentAreaFilled(false);
        jButtonOpClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpClearActionPerformed(evt);
            }
        });

        jButtonOpDeletar.setBackground(new java.awt.Color(230, 230, 230));
        jButtonOpDeletar.setText("DEL");
        jButtonOpDeletar.setBorder(null);
        jButtonOpDeletar.setContentAreaFilled(false);
        jButtonOpDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpDeletarActionPerformed(evt);
            }
        });

        jButtonNum7.setBackground(new java.awt.Color(230, 230, 230));
        jButtonNum7.setText("7");
        jButtonNum7.setBorder(null);
        jButtonNum7.setContentAreaFilled(false);
        jButtonNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum7ActionPerformed(evt);
            }
        });

        jButtonNum8.setBackground(new java.awt.Color(230, 230, 230));
        jButtonNum8.setText("8");
        jButtonNum8.setBorder(null);
        jButtonNum8.setContentAreaFilled(false);
        jButtonNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum8ActionPerformed(evt);
            }
        });

        jButtonNum9.setBackground(new java.awt.Color(230, 230, 230));
        jButtonNum9.setText("9");
        jButtonNum9.setBorder(null);
        jButtonNum9.setContentAreaFilled(false);
        jButtonNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum9ActionPerformed(evt);
            }
        });

        jButtonOpSinal.setBackground(new java.awt.Color(230, 230, 230));
        jButtonOpSinal.setText("+/-");
        jButtonOpSinal.setBorder(null);
        jButtonOpSinal.setContentAreaFilled(false);
        jButtonOpSinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpSinalActionPerformed(evt);
            }
        });

        jButtonNum0.setBackground(new java.awt.Color(230, 230, 230));
        jButtonNum0.setText("0");
        jButtonNum0.setBorder(null);
        jButtonNum0.setContentAreaFilled(false);
        jButtonNum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum0ActionPerformed(evt);
            }
        });

        jButtonOpPonto.setBackground(new java.awt.Color(230, 230, 230));
        jButtonOpPonto.setText(".");
        jButtonOpPonto.setBorder(null);
        jButtonOpPonto.setContentAreaFilled(false);
        jButtonOpPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpPontoActionPerformed(evt);
            }
        });

        jButtonNum4.setBackground(new java.awt.Color(230, 230, 230));
        jButtonNum4.setText("4");
        jButtonNum4.setBorder(null);
        jButtonNum4.setContentAreaFilled(false);
        jButtonNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum4ActionPerformed(evt);
            }
        });

        jButtonNum5.setBackground(new java.awt.Color(230, 230, 230));
        jButtonNum5.setText("5");
        jButtonNum5.setBorder(null);
        jButtonNum5.setContentAreaFilled(false);
        jButtonNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum5ActionPerformed(evt);
            }
        });

        jButtonNum6.setBackground(new java.awt.Color(230, 230, 230));
        jButtonNum6.setText("6");
        jButtonNum6.setBorder(null);
        jButtonNum6.setContentAreaFilled(false);
        jButtonNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum6ActionPerformed(evt);
            }
        });

        jButtonNum1.setBackground(new java.awt.Color(230, 230, 230));
        jButtonNum1.setText("1");
        jButtonNum1.setBorder(null);
        jButtonNum1.setContentAreaFilled(false);
        jButtonNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum1ActionPerformed(evt);
            }
        });

        jButtonNum2.setBackground(new java.awt.Color(230, 230, 230));
        jButtonNum2.setText("2");
        jButtonNum2.setBorder(null);
        jButtonNum2.setContentAreaFilled(false);
        jButtonNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum2ActionPerformed(evt);
            }
        });

        jButtonNum3.setBackground(new java.awt.Color(230, 230, 230));
        jButtonNum3.setText("3");
        jButtonNum3.setBorder(null);
        jButtonNum3.setContentAreaFilled(false);
        jButtonNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum3ActionPerformed(evt);
            }
        });

        jButtonOpMultiplicacao.setBackground(new java.awt.Color(230, 230, 230));
        jButtonOpMultiplicacao.setText("X");
        jButtonOpMultiplicacao.setBorder(null);
        jButtonOpMultiplicacao.setContentAreaFilled(false);
        jButtonOpMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpMultiplicacaoActionPerformed(evt);
            }
        });

        jButtonOpSubtracao.setBackground(new java.awt.Color(230, 230, 230));
        jButtonOpSubtracao.setText("-");
        jButtonOpSubtracao.setBorder(null);
        jButtonOpSubtracao.setContentAreaFilled(false);
        jButtonOpSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpSubtracaoActionPerformed(evt);
            }
        });

        jButtonOpDivUm.setBackground(new java.awt.Color(230, 230, 230));
        jButtonOpDivUm.setText("1/x");
        jButtonOpDivUm.setBorder(null);
        jButtonOpDivUm.setContentAreaFilled(false);
        jButtonOpDivUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpDivUmActionPerformed(evt);
            }
        });

        jButtonOpDivisao.setBackground(new java.awt.Color(230, 230, 230));
        jButtonOpDivisao.setText("/");
        jButtonOpDivisao.setBorder(null);
        jButtonOpDivisao.setContentAreaFilled(false);
        jButtonOpDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpDivisaoActionPerformed(evt);
            }
        });

        jButtonOpAdicao.setBackground(new java.awt.Color(230, 230, 230));
        jButtonOpAdicao.setText("+");
        jButtonOpAdicao.setBorder(null);
        jButtonOpAdicao.setContentAreaFilled(false);
        jButtonOpAdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpAdicaoActionPerformed(evt);
            }
        });

        jButtonOpResultado.setBackground(new java.awt.Color(230, 230, 230));
        jButtonOpResultado.setText("=");
        jButtonOpResultado.setBorder(null);
        jButtonOpResultado.setContentAreaFilled(false);
        jButtonOpResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpResultadoActionPerformed(evt);
            }
        });

        Painel.setEditable(false);
        Painel.setBackground(new java.awt.Color(242, 242, 242));
        Painel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        Painel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Painel.setBorder(null);
        Painel.setDragEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonOpSinal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonOpPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonOpLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonOpClear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonOpDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonOpPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonOpRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonOpPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonOpDivUm, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonOpDivisao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonOpMultiplicacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonOpSubtracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonOpAdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jButtonOpResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Painel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Painel, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonOpDivUm, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOpDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOpMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonOpPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonOpRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonOpPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonOpLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonOpClear, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonOpDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonOpSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonOpAdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonOpSinal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonOpPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonOpResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String valor = "0";
    private int op = 0;
    
    private void jButtonNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum0ActionPerformed
        // Clique numero 0
        String text = Painel.getText();
        text = text + "0";
        Painel.setText(text);
    }//GEN-LAST:event_jButtonNum0ActionPerformed

    private void jButtonNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum1ActionPerformed
        // Clique numero 1
        String text = Painel.getText();
        text = text + "1";
        Painel.setText(text);
    }//GEN-LAST:event_jButtonNum1ActionPerformed

    private void jButtonNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum2ActionPerformed
        // Clique numero 2
        String text = Painel.getText();
        text = text + "2";
        Painel.setText(text);
    }//GEN-LAST:event_jButtonNum2ActionPerformed

    private void jButtonNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum3ActionPerformed
        // Clique numero 3
        String text = Painel.getText();
        text = text + "3";
        Painel.setText(text);
    }//GEN-LAST:event_jButtonNum3ActionPerformed

    private void jButtonNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum4ActionPerformed
        // Clique numero 4
        String text = Painel.getText();
        text = text + "4";
        Painel.setText(text);
    }//GEN-LAST:event_jButtonNum4ActionPerformed

    private void jButtonNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum5ActionPerformed
        // Clique numero 5
        String text = Painel.getText();
        text = text + "5";
        Painel.setText(text);
    }//GEN-LAST:event_jButtonNum5ActionPerformed

    private void jButtonNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum6ActionPerformed
        // Clique numero 6
        String text = Painel.getText();
        text = text + "6";
        Painel.setText(text);
    }//GEN-LAST:event_jButtonNum6ActionPerformed

    private void jButtonNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum7ActionPerformed
        // Clique numero 7
        String text = Painel.getText();
        text = text + "7";
        Painel.setText(text);
    }//GEN-LAST:event_jButtonNum7ActionPerformed

    private void jButtonNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum8ActionPerformed
        // Clique numero 8
        String text = Painel.getText();
        text = text + "8";
        Painel.setText(text);
    }//GEN-LAST:event_jButtonNum8ActionPerformed

    private void jButtonNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum9ActionPerformed
       // Clique numero 9
        String text = Painel.getText();
        text = text + "9";
        Painel.setText(text);
    }//GEN-LAST:event_jButtonNum9ActionPerformed

    private void jButtonOpAdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpAdicaoActionPerformed
        // Operação de Adição
        if(op == 0){
            valor = Painel.getText();
            op = 1;
            Painel.setText("");
        }
        else{
            Painel.setText("ERRO");
        }

    }//GEN-LAST:event_jButtonOpAdicaoActionPerformed

    private void jButtonOpSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpSubtracaoActionPerformed
        // Operação de Subtração
        if(op == 0){
            valor = Painel.getText();
            op = 2;
            Painel.setText("");
        }
        else{
            Painel.setText("ERRO");
        }
    }//GEN-LAST:event_jButtonOpSubtracaoActionPerformed

    private void jButtonOpMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpMultiplicacaoActionPerformed
       // Operação de Multiplicação
        if(op == 0){
            valor = Painel.getText();
            op = 3;
            Painel.setText("");
        }
        else{
            Painel.setText("ERRO");
        }
    }//GEN-LAST:event_jButtonOpMultiplicacaoActionPerformed

    private void jButtonOpDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpDivisaoActionPerformed
        // Operação de Divisão
        if(op == 0){
            valor = Painel.getText();
            op = 4;
            Painel.setText("");
        }
        else{
            Painel.setText("ERRO");
        }
    }//GEN-LAST:event_jButtonOpDivisaoActionPerformed

    private void jButtonOpRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpRaizActionPerformed
        // Operação de Raiz Quadrada
        if(op == 0){
            float num = Float.parseFloat(Painel.getText());
            Painel.setText(String.valueOf(sqrt(num)));
        }
        else{
            Painel.setText("Erro");
        }
    }//GEN-LAST:event_jButtonOpRaizActionPerformed

    private void jButtonOpPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpPotenciaActionPerformed
        // Operação Elevado a 2
        if(op == 0){
            float num = Float.parseFloat(Painel.getText());
            Painel.setText(String.valueOf(pow(num,2.0)));
        }
        else{
            Painel.setText("Erro");
        }
    }//GEN-LAST:event_jButtonOpPotenciaActionPerformed

    private void jButtonOpDivUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpDivUmActionPerformed
        // Operação Inverso
        if(op == 0){
            float num = Float.parseFloat(Painel.getText());
            if(num != 0){
                Painel.setText(String.valueOf(1/num));
            }
            else
            {
                Painel.setText("Erro");
            }
        }
        else{
            Painel.setText("Erro");
        }
    }//GEN-LAST:event_jButtonOpDivUmActionPerformed

    private void jButtonOpResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpResultadoActionPerformed
        // Resultado
        float valor1 = Float.parseFloat(valor);
        float valor2 = Float.parseFloat(Painel.getText());
        switch (op) {
            case 1:
                // Adição
                Painel.setText(String.valueOf(valor1 + valor2));
                break;
            case 2:
                // Subtração
                Painel.setText(String.valueOf(valor1 - valor2));
                break;
            case 3:
                // Multiplicação
                Painel.setText(String.valueOf(valor1 * valor2));
                break;
            case 4:
                // Divisão
                if(valor2 != 0){
                    Painel.setText(String.valueOf(valor1 / valor2));
                }
                else{
                    Painel.setText("Erro");
                }
                break;
            case 5:
                // Modulo
                Painel.setText(String.valueOf(valor1 % valor2));
                break;
            default:
                break;
        }
        op = 0;
    }//GEN-LAST:event_jButtonOpResultadoActionPerformed

    private void jButtonOpDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpDeletarActionPerformed
        // Remove ultimo caracter do painel
        String text = Painel.getText();
        if(text.length() > 0){
            Painel.setText(text.substring(0, text.length()-1));
        }
    }//GEN-LAST:event_jButtonOpDeletarActionPerformed

    private void jButtonOpClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpClearActionPerformed
        // Limpa tela
        Painel.setText("");
        op = 0;
    }//GEN-LAST:event_jButtonOpClearActionPerformed

    private void jButtonOpLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpLimparActionPerformed
        // TODO add your handling code here:
        Painel.setText("");
        valor = "";
        op = 0;
    }//GEN-LAST:event_jButtonOpLimparActionPerformed

    private void jButtonOpPorcentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpPorcentagemActionPerformed
        // Operação Modulo
        if(op == 0){
            valor = Painel.getText();
            op = 5;
            Painel.setText("");
        }
        else{
            Painel.setText("ERRO");
        }
    }//GEN-LAST:event_jButtonOpPorcentagemActionPerformed

    private void jButtonOpPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpPontoActionPerformed
        // Botao Ponto
        String text = Painel.getText();
        Painel.setText(text += ".");
    }//GEN-LAST:event_jButtonOpPontoActionPerformed

    private void jButtonOpSinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpSinalActionPerformed
        // Troca sinal do painel
        float text = Float.parseFloat(Painel.getText());
        text = -(text);
        Painel.setText(String.valueOf(text));
    }//GEN-LAST:event_jButtonOpSinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Painel;
    private javax.swing.JButton jButtonNum0;
    private javax.swing.JButton jButtonNum1;
    private javax.swing.JButton jButtonNum2;
    private javax.swing.JButton jButtonNum3;
    private javax.swing.JButton jButtonNum4;
    private javax.swing.JButton jButtonNum5;
    private javax.swing.JButton jButtonNum6;
    private javax.swing.JButton jButtonNum7;
    private javax.swing.JButton jButtonNum8;
    private javax.swing.JButton jButtonNum9;
    private javax.swing.JButton jButtonOpAdicao;
    private javax.swing.JButton jButtonOpClear;
    private javax.swing.JButton jButtonOpDeletar;
    private javax.swing.JButton jButtonOpDivUm;
    private javax.swing.JButton jButtonOpDivisao;
    private javax.swing.JButton jButtonOpLimpar;
    private javax.swing.JButton jButtonOpMultiplicacao;
    private javax.swing.JButton jButtonOpPonto;
    private javax.swing.JButton jButtonOpPorcentagem;
    private javax.swing.JButton jButtonOpPotencia;
    private javax.swing.JButton jButtonOpRaiz;
    private javax.swing.JButton jButtonOpResultado;
    private javax.swing.JButton jButtonOpSinal;
    private javax.swing.JButton jButtonOpSubtracao;
    // End of variables declaration//GEN-END:variables
}
